chore(deps): bump com.google.devtools.ksp from 1.9.22-1.0.16 to 1.9.23-1.0.20 (#459)
Bumps [com.google.devtools.ksp](https://github.com/google/ksp) from
1.9.22-1.0.16 to 1.9.23-1.0.20.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/google/ksp/releases">com.google.devtools.ksp's
releases</a>.</em></p>
<blockquote>
<h2>1.9.23-1.0.20</h2>
<h2>KSP1 issues fixed</h2>
<ul>
<li>performance optimization for certain workload consists of heavy Java
files, including
<ul>
<li>Replace IdKey's impl with identityHashCode <a
href="https://redirect.github.com/google/ksp/issues/1804">#1804</a></li>
<li>Cache enclosed descriptors by name <a
href="https://redirect.github.com/google/ksp/issues/1808">#1808</a></li>
</ul>
</li>
<li>Add excludedSources to the KSP extension object <a
href="https://redirect.github.com/google/ksp/issues/1793">#1793</a>
thanks to <a
href="https://github.com/bitspittle"><code>@​bitspittle</code></a></li>
</ul>
<h2>KSP2 issues fixed</h2>
<ul>
<li>NoClassDefFoundError for LZ4Factory when trying KSP2 <a
href="https://redirect.github.com/google/ksp/issues/1713">#1713</a></li>
<li>Calling KSType.replace() with original arguments results in <!-- raw
HTML omitted --> <a
href="https://redirect.github.com/google/ksp/issues/1807">#1807</a></li>
<li>Static fields in base class appear in derived classes <a
href="https://redirect.github.com/google/ksp/issues/1744">#1744</a></li>
<li>fix backing field checking for top level callables</li>
<li>support sealed inheritors lookup.</li>
<li>support type alias for getSymbolsWithAnnotation</li>
<li>support more types for reference elements</li>
</ul>
<h2>1.9.23-1.0.19</h2>
<h3>New APIs</h3>
<ul>
<li><a
href="https://redirect.github.com/google/ksp/issues/1708">#1708</a>
<code>SymbolProcessorEnvironment.kspVersion</code></li>
<li><a
href="https://redirect.github.com/google/ksp/issues/1707">#1707</a>
<code>CodeGenerator.associateWithFunctions</code> and
<code>CodeGenerator.associateWithProperties</code></li>
</ul>
<h3>Issues fixed in KSP2</h3>
<ul>
<li><a
href="https://redirect.github.com/google/ksp/issues/1691">#1691</a>
IllegalStateException: Value type not found for value</li>
<li><a
href="https://redirect.github.com/google/ksp/issues/1719">#1719</a> The
order of symbols returned from Resolver.getSymbolsWithAnnotation() is
different</li>
<li><a
href="https://redirect.github.com/google/ksp/issues/1718">#1718</a>
Getting packageName of Kotlin types returns empty String</li>
<li><a
href="https://redirect.github.com/google/ksp/issues/1721">#1721</a>
KSAnnotation packageName is an empty String for a type from a different
module</li>
<li><a
href="https://redirect.github.com/google/ksp/issues/1722">#1722</a>
Resolver.getDeclarationsFromPackage() returns declarations from the
default package when passing in an unknown package</li>
<li><a
href="https://redirect.github.com/google/ksp/issues/1717">#1717</a>
Resolver.getJvmName() returns different results for annotation args</li>
<li><a
href="https://redirect.github.com/google/ksp/issues/1725">#1725</a>
asMemberOf() throws exception with a generic type without arguments</li>
<li><a
href="https://redirect.github.com/google/ksp/issues/1728">#1728</a>
ClassCastException when calling KSType.replace() with empty list</li>
<li><a
href="https://redirect.github.com/google/ksp/issues/1713">#1713</a>
NoClassDefFoundError for LZ4Factory when trying KSP2</li>
<li><a
href="https://redirect.github.com/google/ksp/issues/1665">#1665</a>
NoClassDefFound in ksp.useKSP2=true mode</li>
<li><a
href="https://redirect.github.com/google/ksp/issues/1733">#1733</a> ABI
incompatibility with kotlin-compiler-embeddable in 2.0.0-Beta4</li>
<li><a
href="https://redirect.github.com/google/ksp/issues/1714">#1714</a>
Generated resources are not added to KotlinCompilation inputs</li>
<li><a
href="https://redirect.github.com/google/ksp/issues/1747">#1747</a>
isCompanionObject is false for companion objects from KOTLIN_LIB</li>
<li><a
href="https://redirect.github.com/google/ksp/issues/1743">#1743</a>
Incorrect type parameter variances</li>
<li><a
href="https://redirect.github.com/google/ksp/issues/1759">#1759</a>
IllegalStateException when getting the modifiers from properties in a
Java annotation declaration</li>
</ul>
<h3>Issues fixed in KSP Gradle Plugin</h3>
<ul>
<li><a
href="https://redirect.github.com/google/ksp/issues/1712">#1712</a>
Analysis API artifacts have the wrong common-deps dependency</li>
<li><a
href="https://redirect.github.com/google/ksp/issues/1775">#1775</a>
1.0.18 creates circular dependencies with kapt tasks</li>
<li><a
href="https://redirect.github.com/google/ksp/issues/1772">#1772</a>
Update plugin com.google.devtools.ksp to v1.9.22-1.0.18 BUILD
FAILED</li>
</ul>
<h3>Known issues</h3>
<ul>
<li><a
href="https://redirect.github.com/google/ksp/issues/1776">#1776</a> KSP2
has higher memory usage when the compile classpath is very large.</li>
</ul>
<h2>1.9.22-1.0.17</h2>
<h2>Issues fixed</h2>
<ul>
<li>Annotations missing on KSTypeArgument of typealias <a
href="https://redirect.github.com/google/ksp/issues/1679">#1679</a></li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/google/ksp/commit/a96538743ede1af9a6034bc24a3216871ba0d1b4"><code>a965387</code></a>
UPDATE_KOTLIN_VERSION: 1.9.23</li>
<li><a
href="https://github.com/google/ksp/commit/96361a97ace57198a786fce349c1a4380208f428"><code>96361a9</code></a>
Downgrade Kotlin to 2.0.0-Beta4</li>
<li><a
href="https://github.com/google/ksp/commit/ea7e9d2cd4e58ec1380f636ac1f2d26c36df5fbe"><code>ea7e9d2</code></a>
Revert &quot;UPDATE_KOTLIN_VERSION: 1.9.30-dev-2548&quot;</li>
<li><a
href="https://github.com/google/ksp/commit/a2b9298c147737bfe84bf0d998b64574683402e5"><code>a2b9298</code></a>
Revert &quot;UPDATE_KOTLIN_VERSION: 2.0.0-dev-4562&quot;</li>
<li><a
href="https://github.com/google/ksp/commit/cdce1978a1794d11791978406e92fbef45feab2d"><code>cdce197</code></a>
Revert &quot;Downgrade Kotlin to 2.0.0-Beta4&quot;</li>
<li><a
href="https://github.com/google/ksp/commit/4d5849a3a57c16a4a8570629cdf1a1db3935fbb3"><code>4d5849a</code></a>
Revert &quot;UPDATE_KOTLIN_VERSION: 2.0.0-Beta5&quot;</li>
<li><a
href="https://github.com/google/ksp/commit/5418453824ecf936a36805a2bd0b1e8f72f8bb6a"><code>5418453</code></a>
Remove dep to javax.annotation.ParametersAreNonnullByDefault</li>
<li><a
href="https://github.com/google/ksp/commit/70a232306ca4858e3147a799ac92d91debe8d9b1"><code>70a2323</code></a>
UPDATE_KOTLIN_VERSION: 2.0.0-Beta5</li>
<li><a
href="https://github.com/google/ksp/commit/815b7a072d5594ea87062c4c05c0f8acda3e524e"><code>815b7a0</code></a>
Keep more classes in uber jar</li>
<li><a
href="https://github.com/google/ksp/commit/acc00dda9625f31e43e8f4e26b4d51fbec885e28"><code>acc00dd</code></a>
Do not minimize lz4-java</li>
<li>Additional commits viewable in <a
href="https://github.com/google/ksp/compare/1.9.22-1.0.16...1.9.23-1.0.20">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=com.google.devtools.ksp&package-manager=gradle&previous-version=1.9.22-1.0.16&new-version=1.9.23-1.0.20)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Pedro Mangabeira <MaethorNaur@users.noreply.github.com>